---

- name: KAFKA | Create kafka config and log paths
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    recurse: true
  with_items:
    - "{{ kafka_conf_path }}"
    - "{{ kafka_log_path }}"

- name: KAFKA | Copy server config
  template:
    src: "{{ kafka_server_template_path }}"
    dest: "{{ kafka_conf_path }}/server.properties"
    mode: "0640"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  notify: restart kafka

- name: KAFKA | Copy log properties
  template:
    src: "{{ kafka_log4j_template_path }}"
    dest: "{{ kafka_conf_path }}/log4j.properties"
    mode: "0644"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  notify: restart kafka

- name: KAFKA | Remove the meta.properties file when migrating a broker
  ansible.builtin.file:
    path: "{{ kafka_data_path }}/meta.properties"
    state: absent
  notify: restart kafka
  when: kafka_migrate_broker

- name: KAFKA | Enable GC log
  replace:
    path: "{{ kafka_install_path }}/bin/kafka-server-start.sh"
    regexp: ^EXTRA_ARGS=\${EXTRA_ARGS-'-name kafkaServer'}
    replace: EXTRA_ARGS=${EXTRA_ARGS-'-name kafkaServer -loggc'}
  when: kafka_gc_log_enabled

- name: KAFKA | Disable GC log
  replace:
    path: "{{ kafka_install_path }}/bin/kafka-server-start.sh"
    regexp: ^EXTRA_ARGS=\${EXTRA_ARGS-'-name kafkaServer -loggc'}
    replace: EXTRA_ARGS=${EXTRA_ARGS-'-name kafkaServer'}
  when: not kafka_gc_log_enabled

# Previously, the recommendation for vm.swappiness was always to
# set it to 0. This value used to have the meaning “do not swap unless
# there is an out-of-memory condition.” However, the meaning of
# this value changed as of Linux kernel version 3.5-rc1, and that
# change was backported into many distributions, including Red Hat
# Enterprise Linux kernels as of version 2.6.32-303. This changed the
# meaning of the value 0 to “never swap under any circumstances.” It
# is for this reason that a value of 1 is now recommended.
- name: KAFKA | Set vm.swappiness to 1
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
  notify: reboot system

- name: KAFKA | Increase maximum number of hard open files to 100K
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '^\* hard nofile'
    line: '* hard nofile 100000'
  notify: reboot system

- name: KAFKA | Increase maximum number of soft open files to 100K
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '^\* soft nofile'
    line: '* soft nofile 100000'
  notify: reboot system
