---

- name: KAFKA | Monitoring
  import_tasks: monitoring.yml
  tags:
    - monitoring

- name: KAFKA | Install
  import_tasks: install.yml
  tags:
    - install

- name: KAFKA | Configure
  import_tasks: config.yml
  tags:
    - configure

- name: KAFKA | Service
  import_tasks: service.yml
  tags:
    - service

- name: KAFKA | Topics
  import_tasks: topics.yml
  run_once: true
  tags:
    - topics
